---
# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: Kubernetes Cluster
# Uncomment to set environment variables for services such as crio and kubelet.
# For example, configure the cluster to pull images via a proxy.
environment: |
  HTTP_PROXY=http://10.0.0.4:7890
  HTTPS_PROXY=http://10.0.0.4:7890
# NO_PROXY表示对这些地址的请求将不会通过配置的代理发送
  NO_PROXY=127.0.0.1,localhost,master-node,worker-node01,worker-node02,10.0.2.0/24,172.16.1.0/16,172.17.1.0/18
# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.
network:
  # Worker IPs are simply incremented from the control IP.
  control_ip: 10.0.11.10
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    cpu: 2
    memory: 4096
  workers:
    count: 2
    cpu: 1
    memory: 2048
# Mount additional shared folders from the host into each virtual machine.
# Note that the project directory is automatically mounted at /vagrant.
# shared_folders:
#   - host_path: ../images
#     vm_path: /vagrant/images
software:
  box: bento/ubuntu-22.04
  calico: 3.26.0
  # To skip the dashboard installation, set its version to an empty value or comment it out:
  dashboard: 2.7.0
  kubernetes: 1.28.1-00
  os: xUbuntu_22.04